app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    #resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    #resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    #resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    #resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"