imports:
    - { resource: repositories.yml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AppBundle\:
    resource: '../../src/AppBundle/*'
    exclude: '../../src/AppBundle/{Controller,Tests,Entity,Repository}'

  AppBundle\Controller\:
    resource: '../../src/AppBundle/Controller/*'
    public: true

  AppBundle\Business\CommitJournal:
    class: AppBundle\Business\CommitJournal
    arguments:
      - '@doctrine.orm.entity_manager'