<?php

namespace AppBundle\Repository\Documents;


use Doctrine\ORM\EntityRepository;

/**
 * JournalPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalPositionRepository extends EntityRepository
{
}
