<?php

namespace AppBundle\Repository\Documents;

/**
 * JournalPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalPositionRepository extends \Doctrine\ORM\EntityRepository
{
}
